# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Wanjivwa Sinkala Portfolio"
email: ""
description: >-
  Experienced administration and risk manager with a passion for sustainability, financial accountability, and development impact.
twitter_username: ""
github_username: "wanjivwasinkala"
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Lusaka

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Wanjivwa Sinkala"
  avatar : "/assets/images/wanji_pic.jpg"
  bio    : '<div style="text-align: justify;">Qualified in economic policy, M&E, and development studies, I’m driven to learn and apply systems that boost accountability and impact.</div>'
  location: "Zambia"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://wanjivwasinkala.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wanjivwasinkala"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wanjivwasinkala"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      css: "assets/css/custom.css"
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      css: "assets/css/custom.css"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
