# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Wanjivwa Sinkala"
description: "Portfolio and professional profile"
baseurl: "" # leave empty if deploying to your root repo
url: "https://wanjivwasinkala.github.io" # replace USERNAME

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Enable dropdown menus
navigation:
  - title: "About Me"
    url: /aboutme/
  - title: "Projects"
    url: /projects/
  - title: "Resources"
    children:
      - title: "Photos"
        url: /resources/photos/
      - title: "Videos"
        url: /resources/videos/
  - title: "Download CV"
    url: /assets/Wanjivwa_Sinkala_CV.pdf
